edition = "2021"
version = "0.1.0"

[workspace]
resolver = "2"
package.version = "1.0.0"
package.edition = "2021"
members = [ "infer", "lsp", "parser2"]

[workspace.dependencies]
expect-test = "1.5.1"
