[package]
name = "parser"
version.workspace = true
edition.workspace = true

[dependencies]

logos = "*"
nom = "*"
log = "*"
anyhow = "*"
thiserror = "*"
strum_macros = "*"
strum = { version = "*", features = ["derive"] }
