[package]
name = "parser2"
version.workspace = true
edition.workspace = true

[dependencies]
once_cell = "1.17.0"
regex-automata = "0.4.0"
rowan = "0.16"
salsa = "0.23"

[dev-dependencies]
criterion = "0.6"
walkdir = "2.3.3"
expect-test.workspace = true

[[bench]]
name = "parse"
harness = false

